#!/usr/bin/env bash
# script to display "Best School" 9 times and after 9th iteration display "Hi"
i=0
while [ $i -lt 10 ]; do
      echo "Best School"
      (( i++ ))
      if [ $i -eq 9 ]; then
	  echo "Hi"
      fi
done
